- name: Ensure awx is configured
  hosts: awx
  roles:
    - { role: geerlingguy.docker, tags: [docker], docker_install_compose: true }
    # - { role: geerlingguy.pip, pip_install_packages: [docker, docker-compose] }
  tasks:
    - name: Ensure Linux tuning for this server's been done
      tags: disable_ipv6
      ansible.posix.sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
      loop:
        - { key: "net.ipv6.conf.all.disable_ipv6", value: 1 }
        - { key: "net.ipv6.conf.default.disable_ipv6", value: 1 }
        - { key: "net.ipv6.conf.lo.disable_ipv6", value: 1 }
    - name: install basic packages
      package:
        name:
          - nodejs
          - npm
          - git
          - python3-pip
          - unzip
          - ansible
          # - docker.io
    - name: Install docker compose python package
      ansible.builtin.pip:
        name: 
          - docker
          - docker-compose
    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      tags: download
      ansible.builtin.unarchive:
        src: https://github.com/ansible/awx/archive/refs/tags/17.1.0.zip
        dest: /tmp/
        remote_src: yes
