- name: Ensure apache is installed
  package:
    name: apache2
    # state: present

# - name: Ensure apache config file is copied to the host
#   copy:
#     src: mysite.conf
#     dest: /etc/apache2/test.conf

- name: Ensure apache config is updated
  ansible.builtin.template:
    src: apache.j2
    dest: /etc/apache.conf
    owner: www-data
    group: www-data
    mode: '0644'

