- name: Add source repository into sources list
  ansible.builtin.template:
    src: ubuntu-sources.list
    dest: /etc/apt/sources.list
  register: apt_source

- name: ensure ntps server is configured
  ansible.builtin.template:
    src: timesyncd.conf
    dest: /etc/systemd/timesyncd.conf
  notify: restart_timesyncd
  
- name: Update apt repo
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes
  when: apt_source.changed

- name: Install basic packages
  package:
    name: 
      - iotop
      - git
    state: present

- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Ensure timezone is OK
  timezone:
    name: "Asia/Tehran"
