- name: Install ceph requirements
  package:
    name: 
      - systemd
      - python3
      - lvm2
      - docker.io

- name: Ensure local dns record are updated
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      10.10.10.135 g-node1
      10.10.10.136 g-node2
      10.10.10.137 g-node3
      10.10.10.101 ceph01
      10.10.10.102 ceph02
      10.10.10.103 ceph03
